### ISSUE TITLE
ERROR: Service 'cloudmapper' failed to build

### ISSUE THREAD

**Issue by tomisaacson** [sebastientaggart/docker-cloudmapper#3]
I'm running Ubuntu 18.04 and I get:

> You are using pip version 18.0, however version 18.1 is available.
> You should consider upgrading via the 'pip install --upgrade pip' command.
> Creating a virtualenv for this project...
> Pipfile: /opt/cloudmapper/Pipfile
> Using /usr/bin/python2 (2.7.15) to create virtualenv...
> Running virtualenv with interpreter /usr/bin/python2
> New python executable in /root/.local/share/virtualenvs/cloudmapper-3ZMnTcmW/bin/python2
> Also creating executable in /root/.local/share/virtualenvs/cloudmapper-3ZMnTcmW/bin/python
> Installing setuptools, pip, wheel...done.
> Setting project for cloudmapper-3ZMnTcmW to /opt/cloudmapper
> 
> Virtualenv location: /root/.local/share/virtualenvs/cloudmapper-3ZMnTcmW
> Warning: Your Pipfile requires python_version 3.7, but you are using 2.7.15 (/root/.local/share/v/c/bin/python).
>   $ pipenv check will surely fail.
> Warning: Your Pipfile requires python_version 3.7, but you are using 2.7.15 (/root/.local/share/v/c/bin/python).
>   $ pipenv check will surely fail.
> Pipfile.lock not found, creating...
> Locking [dev-packages] dependencies...
> kages/pipenv/utils.py", line 250, in actually_resolve_deps
>     req = Requirement.from_line(dep)
>   File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 704, in from_line
>     line, extras = _strip_extras(line)
> TypeError: 'module' object is not callable
> /usr/local/lib/python3.7/site-packages/pipenv/_compat.py:113: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/pipenv-Uhxb4N-requirements'>
>   warnings.warn(warn_message, ResourceWarning)
> 
> ERROR: Service 'cloudmapper' failed to build: The command '/bin/sh -c pip install pipenv && pipenv --two && pipenv install' returned a non-zero code: 1
>

**Comment by tomisaacson** [comment]
I can see `Warning: Your Pipfile requires python_version 3.7, but you are using 2.7.15 ` above but I can't figure out how to redirect `docker-compose`. I've tried `virtualenv` and `pipenv` - is there some trick to this?

**Comment by tomisaacson** [comment]
I realised that the Python 2 dependency is in Dockerfile:
`RUN pip install pipenv && pipenv --two && pipenv install
`
So by changing `python-dev` to `python3-dev` and changing this line to:
`RUN pip install pipenv && pipenv --three && pipenv install
`
So now I get this far:

> You are using pip version 18.0, however version 18.1 is available.
> You should consider upgrading via the 'pip install --upgrade pip' command.
> Creating a virtualenv for this project...
> Pipfile: /opt/cloudmapper/Pipfile
> Using /usr/local/bin/python3 (3.7.0) to create virtualenv...
> Running virtualenv with interpreter /usr/local/bin/python3
> Using base prefix '/usr/local'
> /usr/local/lib/python3.7/site-packages/virtualenv.py:1041: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
>   import imp
> New python executable in /root/.local/share/virtualenvs/cloudmapper-3ZMnTcmW/bin/python3
> Also creating executable in /root/.local/share/virtualenvs/cloudmapper-3ZMnTcmW/bin/python
> Installing setuptools, pip, wheel...done.
> Setting project for cloudmapper-3ZMnTcmW to /opt/cloudmapper
> 
> Virtualenv location: /root/.local/share/virtualenvs/cloudmapper-3ZMnTcmW
> Pipfile.lock not found, creating...
> Locking [dev-packages] dependencies...
> env/utils.py", line 402, in resolve_deps
>     req_dir=req_dir
>   File "/usr/local/lib/python3.7/site-packages/pipenv/utils.py", line 250, in actually_resolve_deps
>     req = Requirement.from_line(dep)
>   File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 704, in from_line
>     line, extras = _strip_extras(line)
> TypeError: 'module' object is not callable
>

**Comment by rcoup** [comment]
@tomisaacson this at least built for me, not sure if it _works_:

```
$ git diff
diff --git a/Dockerfile b/Dockerfile
index 062763c..1aed623 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -6,7 +6,7 @@
 #
 # This project pulls Cloudmapper and initializes it in a docker container.

-FROM python:alpine
+FROM python:3.7-alpine

 LABEL maintainer="https://github.com/sebastientaggart"

@@ -27,10 +27,12 @@ g++ \
 make \
 freetype-dev \
 libpng-dev \
+openblas \
+openblas-dev \
 git

 RUN git clone https://github.com/duo-labs/cloudmapper.git .
-RUN pip install pipenv && pipenv --two && pipenv install
+RUN pip install pipenv && pipenv install
 RUN pip install --upgrade awscli
 #RUN chmod +x entrypoint.sh && touch config.json
```

**Comment by tomisaacson** [comment]
@rcoup thanks, that's working for me.
